version: "3.9"
services:
  srtrelay:
    image: "ravenium/srtrelay:latest"
    ports:
      - "1337:1337/udp"
    networks:
        - fragforce
    volumes:
        - $PWD/config.toml:/conf/config.toml
  frag_restream_record:
    image: "ravenium/fragconsole:latest"
    ports:
        - "3001:3001"
    command: -s -serverurl http://srtrelay:8081/streams -streamurl srt://srtrelay:1337 -listen 0.0.0.0:3001
    networks:
        - fragforce
    volumes:
        - $PWD/record:/record
networks:
  fragforce:
